import logo from "./logo.png"
import account from './account.png'
import cart from './cart.png'
import wishlist from './wishlist.png'
import facebook from './facebook.png'
import instagram from './instagram.png'
import mail from './mail.png'
import mail2 from './mail2.png'
import phone from './phone.png'
import phone2 from './phone2.png'
import twitter from './twitter.png'
import tractor from './tractor.png'
import hamburger from './hamburgar.png'
import hamburgerW from './hamburgarW.png'
import emojine from './emojione-monotone_tractor.png'
import fluent from './fluent_production-24-regular.png'
import fontisto from './fontisto_ship.png'
import john from './John_Deere-Logo.wine .png'
import farmlogo from './Pepperidge_Farm-Logo.wine.png'
import pexels from './pexels-mark-stebnicki.png'
import steyr from './Steyr_Tractor-Logo.wine.png'
import milk from './The_a2_Milk_Company-Logo.wine.png'
import progressive from './The_Progressive_Farmer-Logo.wine.png'
import pin from "./pin.png"
import jannis from './pexels-jannis-knorr.png'
import product1 from './product1.png'
import product2 from './product2.png'
import product3 from './product3.png'
import product4 from './product4.png'
import product5 from './product5.png'
import product6 from './product6.png'
import product7 from './product7.png'
import product01 from './product01.png'
import product02 from './product02.png'
import product03 from './product03.png'
import product04 from './product04.png'
import product05 from './product05.png'
import product06 from './product06.png'
import product07 from './product07.png'
import product8 from './product8.png'
import product9 from './product9.png'
import product10 from './product10.png'
import product11 from './product11.png'
import product12 from './product12.png'
import product13 from './product13.png'
import product14 from './product14.png'
import product15 from './product15.png'
import product16 from './product16.png'
import product17 from './product17.png'
import product18 from './product18.png'
import product19 from './product19.png'
import product20 from './product20.png'
import mobile1 from "./mobile1.png"
import mobile2 from "./mobile2.png"
import mobile3 from "./mobile3.png"
import mobile4 from "./mobile4.png"
import mobile5 from "./mobile5.png"
import mobile7 from "./mobile7.png"
import mobile8 from "./mobile8.png"
import mobile9 from "./mobile9.png"
import mobile10 from "./mobile10.png"
import mobile11 from "./mobile11.png"
import mobile12 from "./mobile12.png"
import about1 from "./about1.png"
import about2 from "./about2.png"
import about3 from "./about3.png"
import about4 from "./about4.png"
import aboutbackground from "./aboutusbackdropp.png"
import line from "./Line.png"
import machinery from "./machinery.png"
import star from "./star.png"
import home from "./home.png"
import note from "./note.png"
import people from "./people.png"
import servicebackground from "./servicebackdrop.png"
import ship from "./ship.png"
import location from "./location.png"
import absolute from './absolute.png'
import close from "./close.png"
import logo2 from "./logo2.png"
import instagw from "./instagw.png"
import tweetw from "./tweetw.svg"
import facew from "./facew.png"
import maintainbg from './maintainbg.png'
import starr from './starr.png'
import faq from './faq.png'
import person2 from './person2.png'
import person02 from './person02.png'
import person3 from './person3.png'
import plus from './plus.png'
import minus from './minus.png'
import or from './or.png'
import facebok from './facebok.png'
import google from './google.png'
import eye from "./ant-design_eye-invisible-filled.png"
import logout from './logout.png'
import newsletter from './newsletter.svg'
import notification from './notification.svg'
import order from './order.svg'
import password from './password.svg'
import profile from './profile.svg'
import select from './select.png'
import inbox from './undrawmail.png'
import ellipse from './ellipse.png'
import trac1 from './trac1.png'
import trac2 from './trac2.png'
import trac3 from './trac3.png'
import trac4 from './trac4.png'
import bin from './delete.png'
import dhl from './dhl.png'
import evergreen from './Evergreen.png'
import fedex from './fedex.png'

const Image={
    bin,dhl,evergreen,fedex,logo,account,cart, wishlist,facebook,instagram,mail,phone,twitter, tractor,
    hamburger,hamburgerW,emojine,fluent,fontisto,john,farmlogo,pexels,steyr,milk, progressive, jannis, product1,product2,product3,product4
,product5,product6,product7,product8,product9,product10,product11,product12,product13,product14,product15,product16,product17,product18,product19,product20,mobile1,
mobile2,mobile3,mobile4,mobile5,mobile7,mobile8,mobile9,mobile10,absolute,product01,product02,product03,product04,product05,product06,product07,
mobile11,mobile12,about1,about2,about3,about4,aboutbackground,star,logo2,home,note,people,servicebackground,ship,starr,
line,machinery,close, location,facew,tweetw,instagw,mail2,phone2,pin,maintainbg,or,facebok,google,
person02,person2,ellipse,trac1,trac2,trac3,trac4,faq,person3,inbox,plus,minus,select,eye,notification,profile,newsletter,password,order,logout}
export default Image